apiVersion: apps/v1
kind: DaemonSet
spec:
  selector:
    matchLabels:
      vino-role: vino-builder
  template:
    metadata:
      labels:
        vino-role: vino-builder
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
        - name: libvirt
          command:
            - /tmp/libvirt.sh
          image: quay.io/airshipit/libvirt:latest-ubuntu_bionic
          securityContext:
            privileged: true
            runAsUser: 0
            readOnlyRootFilesystem: false
          volumeMounts:
            - mountPath: /lib/modules
              name: libmodules
              readOnly: true
            - name: var-lib-libvirt
              mountPath: /var/lib/libvirt
              mountPropagation: Bidirectional
            - name: run
              mountPath: /run
            - name: dev
              mountPath: /dev
            - name: cgroup
              mountPath: /sys/fs/cgroup
            - name: logs
              mountPath: /var/log/libvirt
            - name: var-lib-vino-pool
              mountPath: /var/lib/libvirt/vino-pool
            - name: etc-qemu
              mountPath: /etc/libvirt/qemu
            - name: etc-nwfilter
              mountPath: /etc/libvirt/nwfilter
            - name: etc-hooks
              mountPath: /etc/libvirt/hooks
            - name: etc-storage
              mountPath: /etc/libvirt/storage
        - name: sushy
          ports:
            - containerPort: 8000
              hostPort: 8000
          image: quay.io/metal3-io/sushy-tools
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/sushy-emulator"]
          volumeMounts:
            - name: var-run-libvirt
              mountPath: /var/run/libvirt
            - name: var-lib-libvirt
              mountPath: /var/lib/libvirt
        - name: labeler
          image: quay.io/airshipit/nodelabeler
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        - name: vino-builder
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            exec:
              command:
              - cat
              - /tmp/healthy
          securityContext:
            privileged: true
            runAsUser: 0
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 8001
              hostPort: 8001
          image: quay.io/airshipit/vino-builder:latest-ubuntu_bionic
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: flavors
              mountPath: /var/lib/vino-builder/flavors
            - name: flavor-templates
              mountPath: /var/lib/vino-builder/flavor-templates
            - name: network-templates
              mountPath: /var/lib/vino-builder/network-templates
            - name: storage-templates
              mountPath: /var/lib/vino-builder/storage-templates
            - name: pod-tmp
              mountPath: /tmp
            - mountPath: /lib/modules
              name: libmodules
              readOnly: true
            - name: var-lib-libvirt
              mountPath: /var/lib/libvirt
            - name: var-run-libvirt
              mountPath: /var/run/libvirt
            - name: var-lib-vino-pool
              mountPath: /var/lib/libvirt/vino-pool
            - name: run
              mountPath: /run
            - name: dev
              mountPath: /dev
            - name: cgroup
              mountPath: /sys/fs/cgroup
            - name: logs
              mountPath: /var/log/libvirt
      volumes:
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: var-lib-libvirt
          hostPath:
            path: /var/lib/libvirt
        - name: run
          hostPath:
            path: /run
        - name: dev
          hostPath:
            path: /dev
        - name: logs
          hostPath:
            path: /var/log/libvirt
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: var-run-libvirt
          hostPath:
            path: /var/run/libvirt
        - name: flavors
          configMap:
            name: vino-flavors
            defaultMode: 0555
        - name: flavor-templates
          configMap:
            name: vino-flavor-templates
            defaultMode: 0555
        - name: network-templates
          configMap:
            name: vino-network-templates
            defaultMode: 0555
        - name: storage-templates
          configMap:
            name: vino-storage-templates
            defaultMode: 0555
        - name: pod-tmp
          emptyDir: {}
        - name: var-lib-vino-pool
          hostPath:
            path: /var/lib/vino-pool
            type: DirectoryOrCreate
        - name: etc-qemu
          hostPath:
            path: /etc/vino-qemu
            type: DirectoryOrCreate
        - name: etc-storage
          hostPath:
            path: /etc/vino-storage
            type: DirectoryOrCreate
        - name: etc-nwfilter
          hostPath:
            path: /etc/vino-nwfilter
            type: DirectoryOrCreate
        - name: etc-hooks
          hostPath:
            path: /etc/vino-hooks
            type: DirectoryOrCreate
