libvirtNetworks:
  management:
    libvirtTemplate: |
      <network>
        <name>{{ network.name }}</name>
        <forward mode='route'/>
        <bridge name='{{ network.bridgeName | default('vm-infra-bridge') }}' stp='off' delay='0'/>
        <ip address='{{ network.bridgeIP | default(omit) }}' netmask='{{ ipam.bridge_subnet_netmask }}'>
          <!-- <tftp root='/srv/tftp'/> -->
          <dhcp>
            <range start='{{ ipam.instance_ips[0] }}' end='{{ ipam.instance_ips[-1] }}'/>
            <bootp file='http://{{ pxeBootImageHost | default(ansible_default_ipv4.address) }}:{{ pxeBootImageHostPort | default(80) }}/dualboot.ipxe'/>
          </dhcp>
        </ip>
      </network>
