libvirtNetworks:
  - name: pxe
    libvirtTemplate: |
      <network>
        <name>pxe</name>
        <forward mode='nat'/>
        <bridge name='pxe' stp='off' delay='0'/>
        <ip address='10.153.241.1' netmask='255.255.255.0'>
          <!-- <tftp root='/srv/tftp'/> -->
          <dhcp>
            <range start='10.153.241.2' end='10.153.241.254'/>
            <bootp file='http://{{ pxeBootImageHost | default(ansible_default_ipv4.address) }}:{{ pxeBootImageHostPort | default(80) }}/dualboot.ipxe'/>
          </dhcp>
        </ip>
      </network>
