# Note: IPPools are intended to be created and managed by ViNO itself.
# ViNO will perform IPAM based on end user input in the ViNO CR.
# This resource here is just a reference.
apiVersion: airship.airshipit.org/v1
kind: IPPool
metadata:
  name: ippool-sample
spec:
  subnet: 10.0.0.0/16
  macPrefix: "02:00:00:00:00:00"
  nextMAC: "02:00:00:00:00:03"
  ranges:
    - start: 10.0.0.1
      stop:  10.0.0.9
    - start: 10.0.1.1
      stop:  10.0.1.9
  allocatedIPs:
    - allocatedTo: default-vino-test-cr-leviathan-worker-0
      ip: 10.0.0.1
      mac: "02:00:00:00:00:00"
    - allocatedTo: default-vino-test-cr-leviathan-worker-1
      ip: 10.0.0.2
      mac: "02:00:00:00:00:01"
    - allocatedTo: default-vino-test-cr-leviathan-worker-2
      ip: 10.0.1.1
      mac: "02:00:00:00:00:02"
