apiVersion: airship.airshipit.org/v1
kind: Vino
metadata:
  name: vino-with-template
spec:
  daemonSetOptions:
    namespacedName:
      name: libvirt-template
      namespace: default
  nodeSelector:
    matchLabels:
      beta.kubernetes.io/os: linux
  configuration:
    cpuExclude: 0-4,54-60
    redfishCredentialSecret:
      name: redfishSecret