apiVersion: airship.airshipit.org/v1
kind: Vino
metadata:
  name: vino-test-cr
  #  labels: ...
spec:
  nodeSelector:
    matchLabels:
      beta.kubernetes.io/os: linux
  configuration:
      cpuExclude: 0-4,54-60
      redfishCredentialSecret:
          name: redfishSecret
  networks:
      vmInterfaceName: lo
