apiVersion: airship.airshipit.org/v1
kind: Vino
metadata:
  name: vino-test-cr
  labels: {}
spec:
  nodeLabelKeysToCopy:
    - "airshipit.org/server"
    - "airshipit.org/rack"
  nodeSelector:
    matchLabels:
      beta.kubernetes.io/os: linux
  configuration:
    cpuExclude: 0-1
  networks:
    - name: management
      libvirtTemplate: management
      subnet: 192.168.2.0/20
      instanceSubnet: 192.168.4.0/22
      type: bridge
      allocationStart: 192.168.2.10
      allocationStop: 192.168.2.24 # docs should specify that the range should = number of vms (to permit future expansion over multiple vino crs etc)
      dns_servers: ["135.188.34.124"]
      macPrefix: "52:54:00:06:00:00"
      physicalInterface: enp3s7
      bridgeName: vm-infra
  nodes:
    - name: master
      count: 1
      bmhLabels:
        airshipit.org/k8s-role: master
      networkDataTemplate:
        name: "test-template"
        namespace: "default"
      bootInterfaceName: management
      networkInterfaces:
        - name: management
          type: network
          network: management
          mtu: 1500
      enableVNC: true
  bmcCredentials:
    username: admin
    password: passw0rd
