apiVersion: airship.airshipit.org/v1
kind: Vino
metadata:
  name: vino
  #  labels: ...
spec:
  nodeSelector:
    matchLabels:
      node-type: worker
  configuration:
      cpuExclude: 0-4,54-60
      redfishCredentialSecret:
          name: redfishSecret
