apiVersion: airship.airshipit.org/v1
kind: Vino
metadata:
  name: vino-test-cr
  labels: {}
spec:
  nodeLabelKeysToCopy:
    - "airshipit.org/server"
    - "airshipit.org/rack"
  nodeSelector:
    matchLabels:
      beta.kubernetes.io/os: linux
  configuration:
    cpuExclude: 0-1
  networks:
    - name: management
      libvirtTemplate: management
      subnet: 192.168.2.0/20
      dhcpAllocationStart: 192.168.4.0
      dhcpAllocationStop: 192.168.7.255
      instanceSubnetBitStep: 6
      type: bridge
      staticAllocationStart: 192.168.2.10
      staticAllocationStop: 192.168.2.24
      routes:
        - network: 10.0.0.0
          netmask: 255.255.255.0
          gateway: $vinobridge
      dns_servers: ["135.188.34.124"]
      macPrefix: "52:54:00:06:00:00"
      physicalInterface: enp3s7
      bridgeName: vm-infra
  nodes:
    - name: master
      count: 1
      bmhLabels:
        airshipit.org/k8s-role: master
      networkDataTemplate:
        name: "test-template"
        namespace: "default"
      bootInterfaceName: management
      networkInterfaces:
        - name: management
          type: network
          network: management
          mtu: 1500
      enableVNC: true
    - name: worker
      count: 4
      bmhLabels:
        airshipit.org/k8s-role: worker
      networkDataTemplate:
        name: "test-template"
        namespace: "default"
      bootInterfaceName: management
      networkInterfaces:
        - name: management
          type: network
          network: management
          mtu: 1500
  bmcCredentials:
    username: admin
    password: passw0rd
