apiVersion: airship.airshipit.org/v1
kind: Vino
metadata:
  name: vino-test-cr
  labels: {}
spec:
  vmBridge: vm-infra
  nodeLabelKeysToCopy:
    - "airshipit.org/server"
    - "airshipit.org/rack"
  nodeSelector:
    matchLabels:
      beta.kubernetes.io/os: linux
  configuration:
    cpuExclude: 0-1
  networks:
    - name: management
      subnet: 192.168.2.0/20
      type: ipv4
      allocationStart: 192.168.2.10
      allocationStop: 192.168.2.14 # docs should specify that the range should = number of vms (to permit future expansion over multiple vino crs etc)
      routes:
        - network: 10.0.0.0
          netmask: 255.255.255.0
          gateway: $vinobridge # vino will need to populate this from the nodelabel value `airshipit.org/vino.nodebridgegw`
      dns_servers: ["135.188.34.124"]
      macPrefix: "52:54:00:06:00:00"
    - name: pxe
      subnet: 172.3.3.0/24
      type: ipv4
      routes:
        - network: 0.0.0.0
          netmask: 0.0.0.0
          gateway: 172.3.3.1
      allocationStart: 172.3.3.10
      allocationStop: 172.3.3.199
      macPrefix: "52:54:00:09:00:00"
  nodes:
    - name: master
      count: 1
      bmhLabels:
        airshipit.org/k8s-role: master
      networkDataTemplate:
        name: "test-template"
        namespace: "default"
      bootInterfaceName: pxe
      networkInterfaces:
        - name: vm-infra
          type: bridge
          network: management
          mtu: 1500
        - name: pxe
          type: bridge
          network: pxe
          mtu: 1500
  bmcCredentials:
    username: admin
    password: passw0rd
