##########################################
# configure storage                #
##########################################

- name: create storage
  include_tasks: create-storage.yaml
  loop: "{{ libvirtStorage }}"

##########################################
# configure networks                     #
##########################################

- name: create network
  include_tasks: create-network.yaml
  loop: "{{ networks }}"
  loop_control:
    loop_var: network

##########################################
# configure domains                      #
##########################################

- name: allocate domain cores
  core_allocation:
    nodes: "{{ domains }}"
    flavors: "{{ flavors }}"
    exclude_cpu: "{{ configuration.cpuExclude }}"
  register: node_core_map

- name: debug print node_core_map
  debug:
    var: node_core_map

- name: define domain outer loop
  include_tasks: create-domain.yaml
  loop: "{{ domains }}"
  loop_control:
    loop_var: domain


